apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-pod
  template:
    metadata:
      name: alpine
      labels:
        app: production-pod
    spec:
      containers:
        - name: alpine
          image: httpd:2.4-alpine