apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replica
  labels:
    app: web
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: my-aap-pod
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx